version: '3'
services: 
  streamlit:
    build: streamlit/
    depends_on: 
      - fastapi
    ports: 
      - '8502:8502'
    networks: 
      - steel_network
    container_name: streamlit

  fastapi:
    build: fastapi/
    depends_on: 
      - tf_serving
    ports: 
      - '8000:8000'
    networks: 
      - steel_network
    container_name: fastapi

  tf_serving:
    build: serving/
    ports: 
      - '8501:8501'
    volumes: 
      - ./serving/models/:/models
    command: --rest_api_port=8501 --model_config_file='/models/models.config'
    networks: 
      - steel_network
    container_name: tf_serving
networks:
    steel_network:
        driver: bridge