version: '3'
services: 
  streamlit:
    build: streamlit/Dockerfile
    depends_on: fastapi
    ports: 
      - '8501:8501'
    networks: steel_network
    container_name: streamlit_container
  fastapi:
    build: fastapi/Dockerfile
    depends_on: serving
    ports: 
      - '8000:8000'
    networks: steel_network
    container_name: fastapi_container
  serving:
    build: models/Dockerfile
    ports: 
      - '8502:8501'
    networks: steel_network
    volumes: '/mnt/r/stramlit_and_fastapi/steel_segmentatioln/models/':'/models/'
    command: --rest_api_port=8502 --model_config_file='/models/models.config'

networks:
    steel_network:
        driver: bridge
  